// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: categories.sql

package sqlc

import (
	"context"
)

const getCategoryBySlug = `-- name: GetCategoryBySlug :one
SELECT id, name, slug, image_path, description
FROM categories
WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetCategoryBySlug(ctx context.Context, slug string) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategoryBySlug, slug)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.ImagePath,
		&i.Description,
	)
	return i, err
}

const getServiceNumberByCategoryID = `-- name: GetServiceNumberByCategoryID :one
SELECT COUNT(*)
FROM services
WHERE category_id = $1 AND status = 'active'
`

func (q *Queries) GetServiceNumberByCategoryID(ctx context.Context, categoryID int32) (int64, error) {
	row := q.db.QueryRowContext(ctx, getServiceNumberByCategoryID, categoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, slug, image_path, description
FROM categories
ORDER BY id ASC
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.ImagePath,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoryIDs = `-- name: ListCategoryIDs :many
SELECT id
FROM categories
ORDER BY id ASC
`

func (q *Queries) ListCategoryIDs(ctx context.Context) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, listCategoryIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int32{}
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
