// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: service_feedbacks.sql

package sqlc

import (
	"context"
	"time"
)

const createServiceFeedback = `-- name: CreateServiceFeedback :exec
INSERT INTO service_feedbacks (service_id, user_id, content)
VALUES ($1, $2, $3)
`

type CreateServiceFeedbackParams struct {
	ServiceID int32  `json:"service_id"`
	UserID    int32  `json:"user_id"`
	Content   string `json:"content"`
}

func (q *Queries) CreateServiceFeedback(ctx context.Context, arg CreateServiceFeedbackParams) error {
	_, err := q.db.ExecContext(ctx, createServiceFeedback, arg.ServiceID, arg.UserID, arg.Content)
	return err
}

const listServiceFeedbacks = `-- name: ListServiceFeedbacks :many
SELECT "users"."full_name", "service_feedbacks"."content", "service_feedbacks"."created_at"
FROM "service_feedbacks"
         INNER JOIN "services" ON "services"."id" = "service_feedbacks"."service_id"
         INNER JOIN "users" ON "users"."id" = "service_feedbacks"."user_id"
WHERE "service_feedbacks"."service_id" = $1
`

type ListServiceFeedbacksRow struct {
	FullName  string    `json:"full_name"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) ListServiceFeedbacks(ctx context.Context, serviceID int32) ([]ListServiceFeedbacksRow, error) {
	rows, err := q.db.QueryContext(ctx, listServiceFeedbacks, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServiceFeedbacksRow{}
	for rows.Next() {
		var i ListServiceFeedbacksRow
		if err := rows.Scan(&i.FullName, &i.Content, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
