// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: users.sql

package sqlc

import (
	"context"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (full_name, email, phone, role_id, hashed_password)
VALUES ($1, $2, $3, $4, $5)
`

type CreateUserParams struct {
	FullName string `json:"full_name"`
	Email    string `json:"email"`
	Phone    string `json:"phone"`
	RoleID   int32  `json:"role_id"`
	Password string `json:"hashed_password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.FullName,
		arg.Email,
		arg.Phone,
		arg.RoleID,
		arg.Password,
	)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, full_name, email, phone, address, role_id, hashed_password, created_at
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.RoleID,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, full_name, email, phone, address, role_id, hashed_password, created_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.RoleID,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}

const isProviderRole = `-- name: IsProviderRole :one
SELECT EXISTS (SELECT 1
               FROM users u
               WHERE u.id = $1
                 AND u.role_id = (SELECT id FROM roles WHERE name = 'provider')) AS is_provider
`

func (q *Queries) IsProviderRole(ctx context.Context, id int32) (bool, error) {
	row := q.db.QueryRowContext(ctx, isProviderRole, id)
	var is_provider bool
	err := row.Scan(&is_provider)
	return is_provider, err
}

const isUserExist = `-- name: IsUserExist :one
SELECT EXISTS(SELECT true FROM users WHERE id = $1)
`

func (q *Queries) IsUserExist(ctx context.Context, id int32) (bool, error) {
	row := q.db.QueryRowContext(ctx, isUserExist, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
